### ISSUE TITLE
Build Android fail

### ISSUE THREAD

**Issue by YvesCheung** [iampawan/Flutter-Instagram-UI-Clone#6]
Launching lib/main.dart on MI 9 SE in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/yvescheung/.gradle/caches/transforms-2/files-2.1/8bebf6c82e74cef171815cf060940ce9/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

  /Users/yvescheung/.gradle/caches/transforms-2/files-2.1/8bebf6c82e74cef171815cf060940ce9/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 12s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by YvesCheung** [comment]
com.android.support:support-core-utils:28.0.0
+--- com.android.support:support-core-ui:28.0.0
|    \--- com.android.support:support-fragment:28.0.0
|         \--- io.flutter:flutter_embedding_debug:1.0.0-e1e6ced81d029258d449bdec2ba3cddca9c2ca0c
|              \--- debugRuntimeClasspath

My Flutter engine integrates `com.android.support` v28.
Set `android.compileSdkVersion 28` can solve this problem.

**Comment by 0oooooooo0** [comment]
I had the same problem and solved it.

1.Go to `android/app/bundle.gradle.`
2. The `compileSdkVersion` of line 18 should be 27, but correct it to 28.
3. Success
